baseURL = 'https://hulububble.site/'
defaultContentLanguage = "zh"
languageCode = 'zh'
title = 'Hulu'
theme = 'dream'

enableGitInfo = true

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

author = "Hulu"
description = "A record for Hulu's plan B."
avatar = "/img/personal/avatar.jpg"
headerTitle = "Hulu's Blog"

showSummaryCoverInPost = false
imageZoomableInPost = true
